# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61964eb05585630a8262d4ec02474f5c54c131e2b720c790f3270e41932770f561f6d1b949bd2edc15de2423d74ce77acb204c2e7a0c02403c6c2ea43d1ce167

test:
  secret_key_base: 7430da20561a579aaf01cfd2a4d977ea0ecf3fe085c0225ed092faa9d366835587bbe97036b10e70661354f66b14c2483de2c54324196754b069e2511287c62f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
