# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7212931fa2febe18da644928f9d88df7f66a20a5655d599411d92ff284357783fb71a7768241c690b591d2ea07f8e76b30a2a9e2a8511dce1eacb508bd53be6c

test:
  secret_key_base: b9d29e46e281623cca21ae81c290003ea4611139c9d6642fc4c9143e4bd4737c9afc186aa0b24537b445c31ee64adfad49ea7e15e4c27d2f759962a7ea1c8b10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
